name: collection_gen
description: Collections generator.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  build_runner: ^2.4.4
  glob: ^2.1.2
  source_gen: ^1.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
