name: factory_mapper
description: Collections generator.
version: 1.0.1
repository: https://github.com/lapuske/factory_mapper

environment:
  sdk: ^3.0.3

dependencies:
  analyzer: '>=5.13.0 <10.0.0'
  build: ^4.0.2
  build_runner: ^2.10.1
  glob: ^2.1.2
  source_gen: '>=3.1.0 <5.0.0'

dev_dependencies:
  lints: '>=2.0.0 <7.0.0'
  test: ^1.21.0
